export const jsonCryptoPanic = {
  count: 200,
  next: "https://cryptopanic.com/api/v1/posts/?auth_token=f47f3b7720794b90ddeee7e0474780bb0cf1fcae&page=2",
  previous: null,
  results: [
    {
      kind: "news",
      domain: "u.today",
      source: { title: "U.Today", region: "en", domain: "u.today", path: null },
      title:
        "235.4 Million Dogecoin Moved by Top-20 DOGE Whales as Elon Musk Made His Crypto Statement",
      published_at: "2023-03-04T12:20:00Z",
      slug: "2354-Million-Dogecoin-Moved-by-Top-20-DOGE-Whales-as-Elon-Musk-Made-His-Crypto-Statement",
      currencies: [
        {
          code: "DOGE",
          title: "Dogecoin",
          slug: "dogecoin",
          url: "https://cryptopanic.com/news/dogecoin/",
        },
      ],
      id: 17793710,
      url: "https://cryptopanic.com/news/17793710/2354-Million-Dogecoin-Moved-by-Top-20-DOGE-Whales-as-Elon-Musk-Made-His-Crypto-Statement",
      created_at: "2023-03-04T12:20:00Z",
      votes: {
        negative: 0,
        positive: 0,
        important: 0,
        liked: 0,
        disliked: 0,
        lol: 0,
        toxic: 0,
        saved: 0,
        comments: 0,
      },
    },
    {
      kind: "news",
      domain: "cryptonews.com",
      source: {
        title: "Cryptonews",
        region: "en",
        domain: "cryptonews.com",
        path: null,
      },
      title:
        "Dogecoin Price Prediction as $650 Million Trading Volume Comes In \u2013 Can DOGE Recover to $0.10 Soon?",
      published_at: "2023-03-04T12:13:00Z",
      slug: "Dogecoin-Price-Prediction-as-650-Million-Trading-Volume-Comes-In-Can-DOGE-Recover-to-010-Soon",
      currencies: [
        {
          code: "DOGE",
          title: "Dogecoin",
          slug: "dogecoin",
          url: "https://cryptopanic.com/news/dogecoin/",
        },
      ],
      id: 17793708,
      url: "https://cryptopanic.com/news/17793708/Dogecoin-Price-Prediction-as-650-Million-Trading-Volume-Comes-In-Can-DOGE-Recover-to-010-Soon",
      created_at: "2023-03-04T12:13:00Z",
      votes: {
        negative: 0,
        positive: 0,
        important: 0,
        liked: 0,
        disliked: 0,
        lol: 0,
        toxic: 0,
        saved: 0,
        comments: 0,
      },
    },
    {
      kind: "media",
      domain: "libsyn.com",
      source: {
        title: "Unchained",
        region: "en",
        domain: "libsyn.com",
        path: null,
      },
      title:
        "The Chopping Block: Is Coinbase\u2019s Base \u2018the Binance Smart Chain for White People\u2019? - Ep. 463",
      published_at: "2023-03-04T12:00:00Z",
      slug: "The-Chopping-Block-Is-Coinbases-Base-the-Binance-Smart-Chain-for-White-People-Ep-463",
      id: 17793686,
      url: "https://cryptopanic.com/news/17793686/The-Chopping-Block-Is-Coinbases-Base-the-Binance-Smart-Chain-for-White-People-Ep-463",
      created_at: "2023-03-04T12:00:00Z",
      votes: {
        negative: 0,
        positive: 0,
        important: 0,
        liked: 0,
        disliked: 0,
        lol: 0,
        toxic: 0,
        saved: 0,
        comments: 0,
      },
    },
    {
      kind: "news",
      domain: "beincrypto.com",
      source: {
        title: "BeInCrypto",
        region: "en",
        domain: "beincrypto.com",
        path: null,
      },
      title:
        "Tether Partners Used Fraudulent Documents to Give Company Access to Bank Accounts, Says Report",
      published_at: "2023-03-04T11:59:00Z",
      slug: "Tether-Partners-Used-Fraudulent-Documents-to-Give-Company-Access-to-Bank-Accounts-Says-Report",
      currencies: [
        {
          code: "USDT",
          title: "Tether",
          slug: "tether",
          url: "https://cryptopanic.com/news/tether/",
        },
      ],
      id: 17793705,
      url: "https://cryptopanic.com/news/17793705/Tether-Partners-Used-Fraudulent-Documents-to-Give-Company-Access-to-Bank-Accounts-Says-Report",
      created_at: "2023-03-04T11:59:00Z",
      votes: {
        negative: 0,
        positive: 0,
        important: 0,
        liked: 0,
        disliked: 0,
        lol: 0,
        toxic: 0,
        saved: 0,
        comments: 0,
      },
    },
    {
      kind: "news",
      domain: "newsbtc.com",
      source: {
        title: "NewsBTC",
        region: "en",
        domain: "newsbtc.com",
        path: null,
      },
      title:
        "This Report Claims Bitcoin NFT Market Will Grow By 2025, But How?",
      published_at: "2023-03-04T11:53:23Z",
      slug: "This-Report-Claims-Bitcoin-NFT-Market-Will-Grow-By-2025-But-How",
      currencies: [
        {
          code: "BTC",
          title: "Bitcoin",
          slug: "bitcoin",
          url: "https://cryptopanic.com/news/bitcoin/",
        },
        {
          code: "SOL",
          title: "Solana",
          slug: "solana",
          url: "https://cryptopanic.com/news/solana/",
        },
      ],
      id: 17793664,
      url: "https://cryptopanic.com/news/17793664/This-Report-Claims-Bitcoin-NFT-Market-Will-Grow-By-2025-But-How",
      created_at: "2023-03-04T11:53:23Z",
      votes: {
        negative: 0,
        positive: 0,
        important: 0,
        liked: 0,
        disliked: 0,
        lol: 0,
        toxic: 0,
        saved: 0,
        comments: 0,
      },
    },
    {
      kind: "news",
      domain: "bitcoinist.com",
      source: {
        title: "Bitcoinist",
        region: "en",
        domain: "bitcoinist.com",
        path: null,
      },
      title:
        "BUSD Active Address Plunges By 60% Following Regulatory Crackdown",
      published_at: "2023-03-04T11:40:36Z",
      slug: "BUSD-Active-Address-Plunges-By-60-Following-Regulatory-Crackdown",
      currencies: [
        {
          code: "BUSD",
          title: "Binance USD",
          slug: "binance-usd",
          url: "https://cryptopanic.com/news/binance-usd/",
        },
      ],
      id: 17793656,
      url: "https://cryptopanic.com/news/17793656/BUSD-Active-Address-Plunges-By-60-Following-Regulatory-Crackdown",
      created_at: "2023-03-04T11:40:36Z",
      votes: {
        negative: 0,
        positive: 0,
        important: 0,
        liked: 0,
        disliked: 0,
        lol: 0,
        toxic: 0,
        saved: 0,
        comments: 0,
      },
    },
    {
      kind: "news",
      domain: "bitcoinist.com",
      source: {
        title: "Bitcoinist",
        region: "en",
        domain: "bitcoinist.com",
        path: null,
      },
      title:
        "Litecoin New Update Not Sufficient To Keep Miners Going \u2013 Here\u2019s Why",
      published_at: "2023-03-04T11:36:32Z",
      slug: "Litecoin-New-Update-Not-Sufficient-To-Keep-Miners-Going-Heres-Why",
      currencies: [
        {
          code: "BTC",
          title: "Bitcoin",
          slug: "bitcoin",
          url: "https://cryptopanic.com/news/bitcoin/",
        },
        {
          code: "LTC",
          title: "Litecoin",
          slug: "litecoin",
          url: "https://cryptopanic.com/news/litecoin/",
        },
      ],
      id: 17793641,
      url: "https://cryptopanic.com/news/17793641/Litecoin-New-Update-Not-Sufficient-To-Keep-Miners-Going-Heres-Why",
      created_at: "2023-03-04T11:36:32Z",
      votes: {
        negative: 0,
        positive: 0,
        important: 0,
        liked: 0,
        disliked: 0,
        lol: 0,
        toxic: 0,
        saved: 0,
        comments: 0,
      },
    },
    {
      kind: "news",
      domain: "bitcoinist.com",
      votes: {
        negative: 1,
        positive: 0,
        important: 0,
        liked: 0,
        disliked: 0,
        lol: 0,
        toxic: 0,
        saved: 1,
        comments: 0,
      },
      source: {
        title: "Bitcoinist",
        region: "en",
        domain: "bitcoinist.com",
        path: null,
      },
      title:
        "Bitfinex And Tether Falsified Documents To Access Bank Services, Report Claims",
      published_at: "2023-03-04T11:00:13Z",
      slug: "Bitfinex-And-Tether-Falsified-Documents-To-Access-Bank-Services-Report-Claims",
      currencies: [
        {
          code: "USDT",
          title: "Tether",
          slug: "tether",
          url: "https://cryptopanic.com/news/tether/",
        },
      ],
      id: 17793598,
      url: "https://cryptopanic.com/news/17793598/Bitfinex-And-Tether-Falsified-Documents-To-Access-Bank-Services-Report-Claims",
      created_at: "2023-03-04T11:00:13Z",
    },
    {
      kind: "news",
      domain: "cryptonews.com",
      source: {
        title: "Cryptonews",
        region: "en",
        domain: "cryptonews.com",
        path: null,
      },
      title:
        "Persisting Gaps, HODLing Coins, Green-Lighting Deals and 20 Crypto Jokes",
      published_at: "2023-03-04T11:00:00Z",
      slug: "Persisting-Gaps-HODLing-Coins-Green-Lighting-Deals-and-20-Crypto-Jokes",
      id: 17793599,
      url: "https://cryptopanic.com/news/17793599/Persisting-Gaps-HODLing-Coins-Green-Lighting-Deals-and-20-Crypto-Jokes",
      created_at: "2023-03-04T11:00:00Z",
      votes: {
        negative: 0,
        positive: 0,
        important: 0,
        liked: 0,
        disliked: 0,
        lol: 0,
        toxic: 0,
        saved: 0,
        comments: 0,
      },
    },
    {
      kind: "news",
      domain: "cointelegraph.com",
      source: {
        title: "CoinTelegraph",
        region: "en",
        domain: "cointelegraph.com",
        path: null,
      },
      title:
        "Jack Dorsey\u2019s TBD launches \u2018C=\u2019 to improve Bitcoin Lightning Network",
      published_at: "2023-03-04T10:50:00Z",
      slug: "Jack-Dorseys-TBD-launches-C-to-improve-Bitcoin-Lightning-Network",
      currencies: [
        {
          code: "BTC",
          title: "Bitcoin",
          slug: "bitcoin",
          url: "https://cryptopanic.com/news/bitcoin/",
        },
      ],
      id: 17793578,
      url: "https://cryptopanic.com/news/17793578/Jack-Dorseys-TBD-launches-C-to-improve-Bitcoin-Lightning-Network",
      created_at: "2023-03-04T10:50:00Z",
      votes: {
        negative: 0,
        positive: 0,
        important: 0,
        liked: 0,
        disliked: 0,
        lol: 0,
        toxic: 0,
        saved: 0,
        comments: 0,
      },
    },
    {
      kind: "media",
      domain: "youtube.com",
      votes: {
        negative: 0,
        positive: 0,
        important: 0,
        liked: 0,
        disliked: 0,
        lol: 0,
        toxic: 0,
        saved: 0,
        comments: 1,
      },
      source: {
        title: "The Modern Investor",
        region: "en",
        domain: "youtube.com",
        path: null,
      },
      title:
        "You Better PRAY That This NEVER HAPPENS... Altcoins Will COLLAPSE",
      published_at: "2023-03-04T10:45:03Z",
      slug: "You-Better-PRAY-That-This-NEVER-HAPPENS-Altcoins-Will-COLLAPSE",
      id: 17793582,
      url: "https://cryptopanic.com/news/17793582/You-Better-PRAY-That-This-NEVER-HAPPENS-Altcoins-Will-COLLAPSE",
      created_at: "2023-03-04T10:45:03Z",
    },
    {
      kind: "news",
      domain: "beincrypto.com",
      source: {
        title: "BeInCrypto",
        region: "en",
        domain: "beincrypto.com",
        path: null,
      },
      title:
        "Silvergate Discontinues Exchange Network After Second Moody\u2019s Downgrade",
      published_at: "2023-03-04T10:40:11Z",
      slug: "Silvergate-Discontinues-Exchange-Network-After-Second-Moodys-Downgrade",
      id: 17793567,
      url: "https://cryptopanic.com/news/17793567/Silvergate-Discontinues-Exchange-Network-After-Second-Moodys-Downgrade",
      created_at: "2023-03-04T10:40:11Z",
      votes: {
        negative: 0,
        positive: 0,
        important: 0,
        liked: 0,
        disliked: 0,
        lol: 0,
        toxic: 0,
        saved: 0,
        comments: 0,
      },
    },
    {
      kind: "news",
      domain: "ambcrypto.com",
      votes: {
        negative: 0,
        positive: 2,
        important: 2,
        liked: 2,
        disliked: 0,
        lol: 1,
        toxic: 0,
        saved: 0,
        comments: 0,
      },
      source: {
        title: "AMBCrypto",
        region: "en",
        domain: "ambcrypto.com",
        path: null,
      },
      title:
        "Ripple survey: Crypto can enable faster transactions, say 97% payment firms",
      published_at: "2023-03-04T10:30:21Z",
      slug: "Ripple-survey-Crypto-can-enable-faster-transactions-say-97-payment-firms",
      currencies: [
        {
          code: "XRP",
          title: "XRP",
          slug: "ripple",
          url: "https://cryptopanic.com/news/ripple/",
        },
      ],
      id: 17793552,
      url: "https://cryptopanic.com/news/17793552/Ripple-survey-Crypto-can-enable-faster-transactions-say-97-payment-firms",
      created_at: "2023-03-04T10:30:21Z",
    },
    {
      kind: "news",
      domain: "theblockcrypto.com",
      source: {
        title: "The Block",
        region: "en",
        domain: "theblockcrypto.com",
        path: null,
      },
      title: "Crypto lender Celsius converts almost 23,000 WBTC into bitcoin",
      published_at: "2023-03-04T10:25:29Z",
      slug: "Crypto-lender-Celsius-converts-almost-23000-WBTC-into-bitcoin",
      currencies: [
        {
          code: "BTC",
          title: "Bitcoin",
          slug: "bitcoin",
          url: "https://cryptopanic.com/news/bitcoin/",
        },
        {
          code: "WBTC",
          title: "Wrapped Bitcoin",
          slug: "wrapped-bitcoin",
          url: "https://cryptopanic.com/news/wrapped-bitcoin/",
        },
      ],
      id: 17793547,
      url: "https://cryptopanic.com/news/17793547/Crypto-lender-Celsius-converts-almost-23000-WBTC-into-bitcoin",
      created_at: "2023-03-04T10:25:29Z",
      votes: {
        negative: 0,
        positive: 0,
        important: 0,
        liked: 0,
        disliked: 0,
        lol: 0,
        toxic: 0,
        saved: 0,
        comments: 0,
      },
    },
    {
      kind: "news",
      domain: "cointelegraph.com",
      votes: {
        negative: 1,
        positive: 0,
        important: 0,
        liked: 2,
        disliked: 1,
        lol: 0,
        toxic: 0,
        saved: 0,
        comments: 0,
      },
      source: {
        title: "CoinTelegraph",
        region: "en",
        domain: "cointelegraph.com",
        path: null,
      },
      title:
        "Bitcoin price would retest $25K without Silvergate saga \u2014 analysis",
      published_at: "2023-03-04T10:18:39Z",
      slug: "Bitcoin-price-would-retest-25K-without-Silvergate-saga-analysis",
      currencies: [
        {
          code: "BTC",
          title: "Bitcoin",
          slug: "bitcoin",
          url: "https://cryptopanic.com/news/bitcoin/",
        },
      ],
      id: 17793524,
      url: "https://cryptopanic.com/news/17793524/Bitcoin-price-would-retest-25K-without-Silvergate-saga-analysis",
      created_at: "2023-03-04T10:18:39Z",
    },
    {
      kind: "news",
      domain: "dailyhodl.com",
      votes: {
        negative: 0,
        positive: 1,
        important: 1,
        liked: 0,
        disliked: 0,
        lol: 0,
        toxic: 0,
        saved: 0,
        comments: 1,
      },
      source: {
        title: "The Daily Hodl",
        region: "en",
        domain: "dailyhodl.com",
        path: null,
      },
      title:
        "Massive Crypto Whale Accumulates 19,801,902,912,350 Shiba Inu (SHIB) and Four Ethereum-Based Altcoins",
      published_at: "2023-03-04T10:15:28Z",
      slug: "Massive-Crypto-Whale-Accumulates-19801902912350-Shiba-Inu-SHIB-and-Four-Ethereum-Based-Altcoins",
      currencies: [
        {
          code: "ETH",
          title: "Ethereum",
          slug: "ethereum",
          url: "https://cryptopanic.com/news/ethereum/",
        },
        {
          code: "DOGE",
          title: "Dogecoin",
          slug: "dogecoin",
          url: "https://cryptopanic.com/news/dogecoin/",
        },
        {
          code: "MATIC",
          title: "Polygon",
          slug: "matic-network",
          url: "https://cryptopanic.com/news/matic-network/",
        },
        {
          code: "SHIB",
          title: "Shiba Inu",
          slug: "shiba-inu",
          url: "https://cryptopanic.com/news/shiba-inu/",
        },
        {
          code: "UNI",
          title: "Uniswap",
          slug: "uniswap",
          url: "https://cryptopanic.com/news/uniswap/",
        },
        {
          code: "LINK",
          title: "Chainlink",
          slug: "chainlink",
          url: "https://cryptopanic.com/news/chainlink/",
        },
      ],
      id: 17793530,
      url: "https://cryptopanic.com/news/17793530/Massive-Crypto-Whale-Accumulates-19801902912350-Shiba-Inu-SHIB-and-Four-Ethereum-Based-Altcoins",
      created_at: "2023-03-04T10:15:28Z",
    },
    {
      kind: "news",
      domain: "bitcoinist.com",
      votes: {
        negative: 0,
        positive: 0,
        important: 0,
        liked: 0,
        disliked: 0,
        lol: 0,
        toxic: 0,
        saved: 0,
        comments: 1,
      },
      source: {
        title: "Bitcoinist",
        region: "en",
        domain: "bitcoinist.com",
        path: null,
      },
      title:
        "MicroStrategy Reassures Investors Of \u2018Minimal Exposure\u2019 To Silvergate",
      published_at: "2023-03-04T09:42:30Z",
      slug: "MicroStrategy-Reassures-Investors-Of-Minimal-Exposure-To-Silvergate",
      id: 17792954,
      url: "https://cryptopanic.com/news/17792954/MicroStrategy-Reassures-Investors-Of-Minimal-Exposure-To-Silvergate",
      created_at: "2023-03-04T09:42:30Z",
    },
    {
      kind: "news",
      domain: "cryptonews.com",
      source: {
        title: "Cryptonews",
        region: "en",
        domain: "cryptonews.com",
        path: null,
      },
      title:
        "Crypto Bank Silvergate Forced to Return $9.85M Deposit to BlockFi in Ongoing Bankruptcy Dispute",
      published_at: "2023-03-04T09:40:00Z",
      slug: "Crypto-Bank-Silvergate-Forced-to-Return-985M-Deposit-to-BlockFi-in-Ongoing-Bankruptcy-Dispute",
      id: 17792968,
      url: "https://cryptopanic.com/news/17792968/Crypto-Bank-Silvergate-Forced-to-Return-985M-Deposit-to-BlockFi-in-Ongoing-Bankruptcy-Dispute",
      created_at: "2023-03-04T09:40:00Z",
      votes: {
        negative: 0,
        positive: 0,
        important: 0,
        liked: 0,
        disliked: 0,
        lol: 0,
        toxic: 0,
        saved: 0,
        comments: 0,
      },
    },
    {
      kind: "news",
      domain: "ambcrypto.com",
      source: {
        title: "AMBCrypto",
        region: "en",
        domain: "ambcrypto.com",
        path: null,
      },
      title:
        "Uniswap enters bridge assessment process, thanks to this committee",
      published_at: "2023-03-04T09:30:57Z",
      slug: "Uniswap-enters-bridge-assessment-process-thanks-to-this-committee",
      currencies: [
        {
          code: "UNI",
          title: "Uniswap",
          slug: "uniswap",
          url: "https://cryptopanic.com/news/uniswap/",
        },
      ],
      id: 17792758,
      url: "https://cryptopanic.com/news/17792758/Uniswap-enters-bridge-assessment-process-thanks-to-this-committee",
      created_at: "2023-03-04T09:30:57Z",
      votes: {
        negative: 0,
        positive: 0,
        important: 0,
        liked: 0,
        disliked: 0,
        lol: 0,
        toxic: 0,
        saved: 0,
        comments: 0,
      },
    },
    {
      kind: "news",
      domain: "dailyhodl.com",
      votes: {
        negative: 0,
        positive: 0,
        important: 0,
        liked: 0,
        disliked: 0,
        lol: 0,
        toxic: 0,
        saved: 0,
        comments: 1,
      },
      source: {
        title: "The Daily Hodl",
        region: "en",
        domain: "dailyhodl.com",
        path: null,
      },
      title:
        "Strategist Who Accurately Predicted 2022 Bitcoin Bottom Details When To Expect Next Massive BTC Rally",
      published_at: "2023-03-04T08:04:40Z",
      slug: "Strategist-Who-Accurately-Predicted-2022-Bitcoin-Bottom-Details-When-To-Expect-Next-Massive-BTC-Rally",
      currencies: [
        {
          code: "BTC",
          title: "Bitcoin",
          slug: "bitcoin",
          url: "https://cryptopanic.com/news/bitcoin/",
        },
      ],
      id: 17790897,
      url: "https://cryptopanic.com/news/17790897/Strategist-Who-Accurately-Predicted-2022-Bitcoin-Bottom-Details-When-To-Expect-Next-Massive-BTC-Rally",
      created_at: "2023-03-04T08:04:40Z",
    },
  ],
};
